Enable publishing to Modrinth.

diff --git a/.github/workflows/build-and-publish.yaml b/.github/workflows/build-and-publish.yaml
--- a/.github/workflows/build-and-publish.yaml
+++ b/.github/workflows/build-and-publish.yaml
@@ -43,14 +43,22 @@ on:
         type: string
         required: false
         default: wrapper
-      gradle-publish:
+      publish-github-packages:
         description: |
-          Whether to run the Gradle `publish` task after uploading artifacts.
+          Whether to publish to GitHub Packages.
 
-          Defaults to `false`.
+          Defaults to `true`.
         type: boolean
         required: false
-        default: false
+        default: true
+      publish-modrinth:
+        description: |
+          Whether to publish to Modrinth.
+
+          Defaults to `true`.
+        type: boolean
+        required: false
+        default: true
       upload-artifacts:
         description: |
           Whether to upload artifacts.
@@ -86,6 +94,10 @@ on:
         description: |
           The token to use when making authenticated calls to the GitHub API.
         required: true
+      modrinth-token:
+        description: |
+          The token to use when making authenticated calls to the Modrinth API.
+        required: false
 jobs:
   build-and-publish:
     name: Build and Publish
@@ -117,11 +129,11 @@ jobs:
               echo "Will be using Java version $(cat .java-version)";
               echo "java-version=$(cat .java-version)" >> "$GITHUB_OUTPUT";
             else
-              echo "::error file=.github\workflows\build.yaml,line=96,endLine=96,title=Missing ``.java-version`` file::No ``.java-version`` file found in the repository but workflow action requested to use it as the source of a Java version to use!";
+              echo "::error file=.github\workflows\build-and-publish.yaml,line=132,endLine=132,title=Missing ``.java-version`` file::No ``.java-version`` file found in the repository but workflow action requested to use it as the source of a Java version to use!";
               exit 1;
             fi
           elif [[ -z "${{inputs.java-version}}" ]]; then
-              echo "::error file=.github\workflows\build.yaml,line=100,endLine=100,title=Missing Java version::No Java version given to build workflow!";
+              echo "::error file=.github\workflows\build-and-publish.yaml,line=136,endLine=136,title=Missing Java version::No Java version given to build workflow!";
               exit 1;
           else
             echo "java-version=${{inputs.java-version}}" >> "$GITHUB_OUTPUT"
@@ -155,10 +167,21 @@ jobs:
           compression-level: 0
           if-no-files-found: error
           retention-days: ${{inputs.artifact-retention-days}}
-      - id: gradle-publish
-        name: Gradle publish
-        if: inputs.gradle-publish
+      - id: publish-github-packages
+        name: Publish to GitHub Packages
+        if: inputs.publish-github-packages
         env:
           GHPR_USERNAME: ${{github.actor}}
           GHPR_TOKEN: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
         run: ./gradlew publish
+      - id: publish-modrinth
+        name: Publish to Modrinth
+        if: inputs.publish-modrinth
+        env:
+          MODRINTH_TOKEN: ${{secrets.modrinth-token}}
+        run: |
+          if [[ -z "${MODRINTH_TOKEN}" ]]; then
+            echo "::error file=.github\workflows\build-and-publish.yaml,line=184,endLine=184,title=No Modrinth API Token::Modrinth publishing requested but no Modrinth API token supplied!";
+            exit 1;
+          fi
+          ./gradlew publish
